name: GitHub Actions Vercel Deploy

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Test:
    if: github.event.pull_request.merged == true
    uses: Madison-T/SPEED_Development_Articles/.github/workflows/test.yml@main

  Deploy-Production:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust based on your project needs

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Variables
        run: vercel env pull .env.local --yes --token=$VERCEL_TOKEN

      - name: Load Environment Variables
        run: |
          if [ -f ".env.local" ]; then
            export $(grep -v '^#' .env.local | xargs);
          fi

      - name: Build Project
        run: npm run build

      - name: Deploy to Vercel Production
        run: vercel deploy --prod --token=$VERCEL_TOKEN --confirm
