name: GitHub Actions Vercel Deploy

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Make sure the Vercel token is stored in GitHub Secrets

jobs:
  Test:
    if: github.event.pull_request.merged == true
    uses: Madison-T/SPEED_Development_Articles/.github/workflows/test.yml@main

  Deploy-Production:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the appropriate version of Node.js for your project

      - name: Install dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build project artifacts
        run: vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
